apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Testing
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/s9r-5/argotags.git'
    targetRevision: shashi/auto-deploy
    directory:
      jsonnet:
        extVars: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
